# Generated by Django 5.2.8 on 2025-12-10 20:22

from django.db import migrations, models

import materials.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "preview",
                    models.ImageField(blank=True, null=True, upload_to="course/preview", verbose_name="Превью"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, validators=[materials.validators.url_validator], verbose_name="Описание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
                "db_table": "course",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, validators=[materials.validators.url_validator], verbose_name="Описание"
                    ),
                ),
                (
                    "preview",
                    models.ImageField(blank=True, null=True, upload_to="lesson/preview", verbose_name="Превью"),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        null=True,
                        validators=[materials.validators.url_validator],
                        verbose_name="Ссылка на видео",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
                "db_table": "lesson",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Подписка",
                "verbose_name_plural": "Подписки",
                "db_table": "subscription",
            },
        ),
    ]
