# Generated by Django 5.2.7 on 2025-10-27 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "preview",
                    models.ImageField(blank=True, null=True, upload_to="course/preview", verbose_name="Превью"),
                ),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
                "db_table": "course",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание")),
                (
                    "preview",
                    models.ImageField(blank=True, null=True, upload_to="lesson/preview", verbose_name="Превью"),
                ),
                ("video_url", models.URLField(blank=True, null=True, verbose_name="Ссылка на видео")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course",
                        to="materials.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
                "db_table": "lesson",
            },
        ),
    ]
