# Generated by Django 6.0 on 2025-12-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_update",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Последнее обновление"),
        ),
    ]
