# Generated by Django 5.2.7 on 2025-10-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("model", models.CharField(max_length=100, verbose_name="Марка")),
                ("title", models.CharField(max_length=120, verbose_name="Модель")),
            ],
            options={
                "verbose_name": "Машина",
                "verbose_name_plural": "Машины",
            },
        ),
    ]
